### ISSUE TITLE
Update ID parameter type for larger value

### ISSUE THREAD

**Issue by benclaussen1** [benclaussen/NetboxPS#49] opened 2023-06-20 13:57 UTC
ID parameters are currently `uint16`. These should be changed to `int64` to match the database type

> I have environment with devices with over 300 000 ids and when i add new machine i got that. 
> 
> PS C:\Windows\system32> Set-NetboxVirtualMachine -Primary_IP4 $NBip.id -Id $vm.id
> Set-NetboxVirtualMachine : Cannot process argument transformation on parameter 'Primary_IP4'. Cannot convert value
> "334039" to type "System.UInt16". Error: "Value was either too large or too small for a UInt16."
> 
> Could you please, advice what i am missing
> 
> _Originally posted by @pendurkov in https://github.com/benclaussen/NetboxPS/discussions/48_

**Comment by RainBawZ** [comment] 2023-06-22 07:50
Assuming IDs cannot be negative, I'd suggest using UInt32 or UInt64, allowing for 4,294,967,295 and 18,446,744,073,709,551,615 unique non-negative IDs respectively.. I feel the latter might be a bit overkill though but by all means, go ham!

**Comment by pendurkov** [comment] 2023-06-22 12:08
Thanks Rain, i tried but still this error. I even overwrite all int16/uint16 with int64/uint64 but still gets from somewhere uint16.

**Comment by RainBawZ** [comment] 2023-06-22 12:24
I'm not quite familiar with this module, but the parameter -Primary_IP4 (and -Primary_IP6 for that matter) seems to be declared as UShort. I don't know if this is correct as my intuition tells me maybe -Primary_IP4 should be of type IPAddress. If it's by design then just ignore it.

That being said, UShort is the same as UInt16. Likewise ULong is the same as UInt64, so try to also replace UShort with UInt64 or ULong

**Comment by benclaussen1** [comment] 2023-06-30 13:17
> I'm not quite familiar with this module, but the parameter -Primary_IP4 (and -Primary_IP6 for that matter) seems to be declared as UShort. I don't know if this is correct as my intuition tells me maybe -Primary_IP4 should be of type IPAddress. If it's by design then just ignore it.
> 
> That being said, UShort is the same as UInt16. Likewise ULong is the same as UInt64, so try to also replace UShort with UInt64 or ULong

This is intentional. The API requires the IP address database ID, so you need to provide that instead of an IP address. This is also a documentation issue on my part since I did not include comment help.

**Comment by pendurkov** [comment] 2023-11-03 15:46
Ben, thanks for your work hard work to increase the values. When i am trying to manually break the function New-NBVirtualMachine and i get that below.  79453  is my eth0 of the VM and 158616 is the IP ID which i wanna assing to it. Could you please advice if I am doing it right?

PS C:\Windows\system32> Set-NetboxIPAMAddress -Assigned_Object_Type virtualization.vminterface -Assigned_Object_Id 79453 -id 158616
Set-NetboxIPAMAddress : Cannot process argument transformation on parameter 'Assigned_Object_Id'. Cannot convert value "79453" to type "System.UInt16". Error: "Value was either too large or too small for a 
UInt16."
At line:1 char:92
+ ... ect_Type virtualization.vminterface -Assigned_Object_Id 79453 -id 158 ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-NetboxIPAMAddress], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-NetboxIPAMAddress

**Comment by benclaussen** [comment] 2023-11-07 14:26
@pendurkov Unfortunately I missed that one. Until I can update the module, you can edit the `Set-NetboxIPAMAddress` function in the PSM1 and change the parameter type for `Assigned_Object_Id` from `[uint16]` to `[uint64]` like the rest.

**Comment by benclaussen** [comment] 2023-11-07 15:31
Fixed in #50

**Closed by benclaussen** 2023-11-07 15:31 UTC
Labels: bug
